# Generated by Django 5.2.12 on 2026-05-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_most_gifted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='New at GlamHub'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_pricedrop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
