# Generated by Django 5.2.12 on 2026-05-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item_is_bestseller_item_is_most_gifted_item_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_bogo',
            field=models.BooleanField(default=False, verbose_name='Buy One Get One'),
        ),
    ]
